# Generated by Django 3.1.7 on 2021-04-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='alias')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('cache_time', models.IntegerField(default=0, help_text='cache time in seconds (specify 0 to not cache)', verbose_name='cache time')),
                ('load_in_template', models.BooleanField(default=False, verbose_name='load in template')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='alias')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('cache_time', models.IntegerField(default=0, help_text='cache time in seconds (specify 0 to not cache)', verbose_name='cache time')),
                ('load_in_template', models.BooleanField(default=False, verbose_name='load in template')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('value', models.TextField(verbose_name='value')),
                ('value_type', models.PositiveSmallIntegerField(choices=[(1, 'Integer'), (2, 'String'), (3, 'Boolean')], default=2, verbose_name='type of value')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_settings.settinggroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
